title: embedded-analog-intelligence
description: views and notes on intelligences
author: matt-chv
github: https://github.com/matt-chv
about: robotics is more than AI, robotics needs AI embedded in the system (fed from real time sensors data and planning and adjusting in real-time its actions).
disqus_shortname: disqus_e5sxXi13p5
google_analytics: UA-XXXXXXXX-Y
#avatar_url: /spark2-fi/static/img/avatar.jpg
avatar_url: /embedded-analog-intelligence/static/img/embedded-analog-intelligence.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
#    - icon: fa-facebook
#      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/matt_chevrier"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/matthieuchevrier"
    - icon: fa-stack-exchange
      link: "https://stackexchange.com/users/13039919/mcv"
    - icon: fa-github
      link: "https://github.com/matt-chv/embedded-analog-intelligence"
    - icon: fa-whatsapp
      link: "https://wa.me/?text=https%3A%2F%2Fmatt-chv.github.io%2Fembedded-analog-intelligence"
    - icon: fa-google-scholar
      link: "https://scholar.google.com/citations?user=gs3enb8AAAAJ&hl=en"
    

share:
  twitter_username: matt-chv
#  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects and Prez
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://matt-chv.github.io"
baseurl: "/embedded-analog-intelligence"
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
